language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "dannkhoma"
    token:
      secure: "CHG1bt/nLbTMNjkikQy95n88v7okOlWLTExJwuWv4T+EWOtkHZy7Pmo7PRHG+P362txFBHQAJQKvpjDY276DhFleJh6yfyrjRwwMrfOXBkgQt75pFy5Rp+PeSMx+spyYQKAJUe04r1l4Q5r8MxeqY5d3VRBS2ghEwaHrbah0iDCUt9hz3uNNHO70aLje8jlPOoPZjpHJBLza//6HtGBP911jQKr2GFv2gvg57kIg1jAy8Lac7QFgeATAezdVZ8h7kmGQ2j6Tv3AkGyRh1yOlMTCalcRPkgCsJ0h78wjqasXbseHNQ+zDux9+5gHJRo942wN9wFaAjsRNQY77PsjR8IntqEPAX47O28OMlnl0KLNSGuF6shEDLZC8q2KE3s9J2qm+LCL/WtA9Y4TlwQ7L/0AFDb9I3zFdFFyL/mPCzP1MUALeQGq/Y6z+cnaxk0fABgNveDJxJ21VL07ptYpxwnhHqr4mtJTIKH2ypihMOYXyt8PXvZaiIaZTR0Xyn5M2IuNo5nyugcbcpdGU9cGkrQYpTYAsgO22hmdZQTaKI7NPkDmgm82Dfhqs/VB/UZ7myay1VtZdnYJ8SLRKrV+6u7sUbiKOfQt47Dk1VEm5vAlapCwRfcRYlD6pEisUVub7hnYhLe2sWjYFktlZqhkPaQ+wnyVwNdTouZ53Pr5wF8s="

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=dannkhoma_client

services:
  - docker

before_install:
  - docker pull dannkhoma/identity
  - docker run -d -p 127.0.0.1:8000:8000

jobs:
  include:
    - stage: build_java_package
      script:
        - mvn clean package

    - stage: build_docker
      script:
        - docker build -f Dockerfile -t user-client:latest .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag user-client "$DOCKER_USERNAME"/user-client
        - docker push "$DOCKER_USERNAME"/user-client