language: java
jdk:
  - openjdk11
  -
env:
  global:
    - secure: "Fb+ukx7IqIKIfh8tXTa+k1jXpl9JgvCumMLXgf/5wG77A4QpsC5vW1VFAWHxGzmWdlpKb20/uF3gN9mJ4v8Wh3Vc/2zACPgRq4KmyC0YDbqQbjkY9vdM6TJnxe1vKK04MsXGEB7oSt+yUduMbaT6znuwkRuDf9qgvldEQG7j97rSDC30ZYxOkRIXoYD65ossAKXmMHe4G4y261QFiYTQqitYkHxhvpLD3lf6I3JIq6z/TXXK4s9XnE0VNuMG9AgqEkqnaT7kyrvFPqRiiSAOnUni9CImmW1KsI+O+wT+hV9BtCVf3FYkSpAwE4RrWVdGOs5V7ToUOtiGURIs96DHLvhXRQbme/RTOEDg/x95cxwJA5C+b/jxPHHg6f9q7mdqMVt7e2/AqpGHEptdoEhSlEYxl0NIOlGZL67CEExUN1lAENnBWWNuQ8yj3e2dlGgTn6DHJ0TDtpKnbqTvk90hXcSg0MTr+ckm/QJSnO67LVvlGVoKCI7reUV+PlAqFnGq10hr0NNnXlpOvvcu0jAnvpqGTgUZpi/BIQFzIltYqOMR2hc00tn3yOqGp0cR3Mgo1BuOAam5sXT8OlQOFxRmr6x+oxl/qYobnVvMRoqaEcxrBNg/eppYJDasNqNrnZwZ3n5qjylUTlASlnxMYS8PUIi/MXYYHmvPNb/00IBjQrc="

addons:
  sonarcloud:
    organization: "dannkhoma"
    token:
      secure: $SONAR_TOKEN

script:
  - ./mvnw clean install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=dannkhoma_client

services:
  - docker