language: java
jdk:
  - openjdk11
  -
env:
  global:
    - secure: "MNv1Q2zFxrMbdiZvLm1+y3OP6GxzGd7AoSLlB60TNCTaur0nhaEgfQsPyXVb0Ol3sWvsTMSzm29GtJnX9bsoGq3gEcZNNTHSEV3NT3obuzrKO0akT3+0oHF39XYWSsBzYomthVFwI3FE1NZ2lyg+PkiSlgLA/HwA/SkrUDaL6NC/Q2E//5jTZww91E5oJs0LNLEPkoTENEypfs0Qb7wnQueVMNcdCCtqUljP1/1hkvYnPud4xfkTYuW2/lpSjAYvkY80BqM7bV0Upjeg+Mpxzc2MPjW4CoLpXrB6OMphFdOaq1EjQSPGJAXx0/8SboCaBnhymCoBZjpto4JICZTE0xT00K0jO6ifdHLvBMrmOYAlAEKZsewgmYBEBBjc8vW9OQ65cJvrkkbtsHmTRRNArg+CQheP7icO+Im0VCYHfqkDyHDusqDje/IyZRSCJMAJ0G8ybyjF5+Moh9fp7BcpGpUVH90vNk2KpcBS4yMAS4R8O+vhpcWLlFnKljivAZCjZwAaTzodQXqpBzfn7TNCRfVVMaOI3QPWoVdpj9sCVo6cEDYkXNuDGYxMatN10WEZtyiklGv8naXhBN3hy4YyT7SJ8MmovvE4huMA6c3wupgcixa7xusZUro8wOiAYrLjlx8io5xCQXWCZFP1xbsPTeCWOaFrTWDfCKkwHSqzP0c="

addons:
  sonarcloud:
    token:
      secure: $SONAR_TOKEN

script:
  - ./mvnw clean install
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

services:
  - docker