language: java
jdk:
  - openjdk11
env:
  global:
    secure: "VxXun9ASGi5sx6ZOrgGKdwT4Ov7N0cOTInBiYsGLUNzt9mZ2bGqIa7Pbttf4EYEHgFDjnQNCeCGy+xbhNsBo9qSnZnELy3P6WfcniRT0hgOed4THKf8EoZ5GG3KiBm8CdeNlDSoA3DLSE0auu9NgQDHPR1bDv3kU1eY8DYN+vWThn6TZir775h9ROZ+rmB8LxOCV+L4ojjCmxcCRUnhhY0YN0VtBquQedrRAGd1IG2AH6fpN1oyVV/rN8fPwhXUMHbRoSShJ3uY6bf43fKhUgpcJsJ70sqJheuWSJd1gKSl2vzGhwxxT/1E2lq1+gerOlekLN1rLeuLA2zUguMuO8UybNnasD9nmk0WuRtQnUCmNScyznsbnYunCYARmMhRiiLAAY2eJQ0WoToFQycW9iTP4QFfxEJDg8xoKnJM4dqjRKqkUwAfoHMRI37Rigm9aDraxjF14401rXmjP/d1I1PuPYcBgrRFQZCyWuYEwCv5BoxRbNnIzaQE++uEI2YDz9QcI2lVIctMrtZgm/fFRb/sHqNK0ZJqtTxmwLZM9JmXao/NuU69700bj1+Awh95LoGDgN8op3EBbDm6VZCdJWN5pehTfCVL9sAnOv1NTmj5plJ6zqp1pQtzBfFyXqi5KjkwHa9T2leyfgR+JJWp/UIn3ug0H8BJs8/7W3obANJE="

addons:
  sonarcloud:
    organization: "dannkhoma"
    token:
      secure: $SONAR_TOKEN

script:
  - ./mvnw clean install
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=dannkhoma_client

services:
  - docker